config/routes.rb
Rails.application.routes.draw do
  get 'book_faq/show'

  resources :posts, only: [:show, :index]

  get 'tags/:tag', to: 'posts#index', as: "tag"
  get 'filter', to: 'posts#filter', as: "filter"
  get 'gimp-book', to: 'book_sales#book', as: "gimp_book"
  get 'privacy-policy', to:'privacy_policy#show', as: "privacy_policy"
  get 'practice-images', to:'practice_images#show', as: "practice_images"
  get 'book-faq', to:'book_faq#show', as: "book_faq"

  mount Dashboard::Engine, at: '/admin'

  Post.where.not(slug: nil).all.each do |blogpost|
     get '/:slug', to: 'posts#slug'
  end
  root to: 'posts#index'

end

app/models/blog_post.rb
class BlogPost < Dashboard::Entry
  # content_attr :body, :text
end

app/models/marketing.rb
class Marketing < Dashboard::Entry
  # content_attr :body, :text
end

app/models/post.rb
class Post < Dashboard::Entry

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper Dashboard::MarkdownHelper

  # def after_sign_in_path_for(resource)
  #   dashboard.entries_path
  # end

end

app/controllers/book_faq_controller.rb
class BookFaqController < ApplicationController
  def show
    @post = Post.new(title: "FAQ", featured_image: "#{view_context.image_url('blackandwhite_desk_image.jpg')}")
  end
end

app/controllers/book_sales_controller.rb
class BookSalesController < ApplicationController
  def book
   render action: "book", layout: "/layouts/book"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :json, :js

  def index
    @post_type = :tutorial
    @posts = Post.published.post_type(@post_type).sorted_by('desc')
  end

  def show
    @post = Post.published.find(params[:id])
  end

  def slug
     @post = Post.published.find_by_slug!(params[:slug])
     render 'show'
  end

  def filter
    @post_type = params[:post_type]
    @posts = Post.published.post_type(params[:post_type]).tagged_with(params[:tag]).content_format(params[:content_format]).sorted_by(params[:order])
    respond_with @posts
  end


  private

  def all_post_types
    Dashboard::Entry.all.published
  end
end

app/controllers/practice_images_controller.rb
class PracticeImagesController < ApplicationController
  
  def show
  end
end

app/controllers/privacy_policy_controller.rb
class PrivacyPolicyController < ApplicationController

  def show
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_faq_helper.rb
module BookFaqHelper
end

app/helpers/book_sales_helper.rb
module BookSalesHelper
end

app/helpers/practice_images_helper.rb
module PracticeImagesHelper
end

app/helpers/privacy_policy_helper.rb
module PrivacyPolicyHelper
end

app/helpers/slug_helper.rb
module SlugHelper
  def path_to_post(post)
    if post.slug && post.slug.length != 0
       post.slug
    else
      post_path(post.id)
    end
  end
end

app/helpers/tag_helper.rb
module TagHelper

  def show_tags(post)
    if post.all_tags.length != 0
      tags = "tags:" + " " + post.all_tags
      tags.html_safe
    else
      return
    end
  end

  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip)}.join(", ")
  end

  def tag_filter(post_type)
    entries = posts_of_type(post_type) #Dashboard::Entry.where(post_type: post_type)
    tag_list = ["All"]
    entries.each do |entry|
      entry.tags.each do |tag|
        tag_list << tag.name
      end
    end
    tag_list.group_by(&:downcase).map do |tag|
      if tag.first == "all"
        ["all (#{posts_of_type(post_type).count})", "all"]
      else
        ["#{tag.first} (#{count_all_posts_of_category(tag)})", tag.first]
     end
   end
  end

  def posts_of_type(post_type)
    Dashboard::Entry.where(post_type: post_type)
  end

  def count_all_posts_of_category(tag)
    tag.second.count
  end

  def count_all_posts_of_format(format, post_type)
    posts_of_type(post_type).where(content_format: format).count
  end
end

app/views/book_faq/show.html.erb
<%= render "layouts/show_paralax" %>
<div class="show-post">
  <h1>Book Purchase Questions</h1>
  <h2>How do I buy this book for my class? Is there an educators discount?</h2>
  <p>At the moment, the book is only available in digital form, so how you buy
    the book for your class depends on how your class will use it.</p>
  <p>Some classes purchase a copy of the book for each computer in their classroom. Others purchase a copy for each student.
  Either way, I'll work with you to get you the apropriate number of copies for your needs.</p>
  <p>I offer a 10% educators discount, just <%= link_to "send me an email", new_contact_message_path %> to get started.</p>

  <h2>How can I buy a print copy?</h2>
  <p>How to GIMP is only available as a digital book at the moment. But, a new
    edition is in the works, and it should be available as both a digital and paperback book!</p>
  <p>Can sign up for email notificationa about the new edition's progress from <%= link_to "the book sales page", gimp_book_path  %>.
    You're also welcome to print your own copy for personal use from the PDF. But please don't distribute printed copies.</p>

  <h1>Questions about GIMP</h1>
  <h2>I lost/accidentally closed my Toolbox! Help!</h2>
  <p>First, try pressing Ctrl B on your keyboard. The Toolbox <i>should</i> reappear.</p>
  <p>If that didn't do the trick, go to Windows > New Toolbox. A new Toolbox should appear.</p>
  <p>It <i>that</i> didn't do the trick, your Toolbox might just be hidden somewhere.
    It might be hiding behind another window, or the pannel it's in might be collapsed.</p>

  <h2>I lost/can't dock my Layers Dialog (or other Dialogs)</h2>
  <p>Watch <a href="https://www.youtube.com/watch?v=S_HC0EkV-AQ">this video</a> on how to find lost dialogs, and how to dock them to the bottom of your Toolbox area.</p>
  <hr>
</div>

app/views/book_sales/_look_inside.html.erb
<div class="look-inside">
  <div class="half">
    <figure>
    <%= image_tag 'landing-cover1.jpg' %>
    <figcaption>
      <!-- <span class="btn-look-inside">Look Inside &#128269;</span> LOOK INSIDE BUTTON< TO BE ACTIVATED WHEN BOOK PREVIEW IS AVAILABLE-->
    </figcaption>
  </figure>
  </div>
  <div class="half">
    <h2>What's Inside</h2>
    <p>Inside "How to GIMP", you'll find over 300 pages of step-by-step instruction,
    tutorials, demonstrations, and screenshots. This isn't some dull white-paper
    or a 5 page report on just a few of GIMP's tools.</p>
    <p>You'll also get over 30 practice images that were crafted to work with the
      tutorials in the book. And they're free!</p>
    <a class="scroll-on-page-link" href="#scroll-link-1">
      <button class="cta-button">Buy the Book</button>
    </a>
  </div>
</div>

app/views/book_sales/_modal.html.erb
<div class="look-inside-modal" id="look-inside-modal">
  <header>
    <h1>Modal Header</h1>
    <span class="modal-close-btn">x</span>
  </header>
  <div class="modal-body">
    This is where the preview will go.
  </div>
</div>

app/views/book_sales/_pricing.html.erb
<section class="book-pricing" id="scroll-link-1">
  <hgroup><h2>Purchase Options</h2></hgroup>

  <div class="book-pricing-content">
    <div class="book-option">
        <h3>
          <%= image_tag 'amazon-logo_black.png', class: 'pricing-file-image amazon' %>
          EPUB
        </h3>
        <span class="price"><sup class="dollar">$</sup>9.99</span>
        <ul>
          <li><em>Kindle</em> Optimised</li>
          <li><em>Instant</em> Download</li>
          <li><em>Same</em> Content as PDF</li>
          <li><em>30+</em> Practice Images</li>
          <li><em>GIMP 2.8</em> Compatible</li>
        </ul>
        <div class="pricing-button">
          <button>Purchase Now</button>
        </div>
    </div>

    <div class="book-option">
      <h3>
        <%= image_tag 'Adobe_PDF_file_icon_32x32.png', class: 'pricing-file-image pdf' %>
        PDF EBOOK
      </h3>
      <span class="price"><sup class="dollar">$</sup>9.99</span>
      <ul>
        <li><em>Desktop</em> Optimised</li>
        <li><em>Instant</em> Download</li>
        <li><em>300+</em> Pages</li>
        <li><em>30+</em> Practice Imges</li>
        <li><em>GIMP 2.8</em> Compatible</li>
      </ul>
      <div class="pricing-button">
        <button>Purchase Now</button>
      </div>
    </div>

    <div class="book-option">
      <h3>
        <%= image_tag 'paperback.png', class: 'pricing-file-image paperback' %>
        Paperback Book
      </h3>
      <span class="price"><sup class="dollar">Coming Soon</sup></span>
     <ul>
       <li><p>A printed paperback edition is in the works! Enter your email address below to get updates
        on its availability.</p>
      </li>
    </ul>
      <div class="email-form" style="margin:10px;">
        <!-- Begin MailChimp Signup Form -->
        <div id="mc_embed_signup">
        <form action="//how-to-gimp.us7.list-manage.com/subscribe/post?u=899fd0460f56466751b56aea7&amp;id=26e918e72d" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
          <div id="mc_embed_signup_scroll">
            <div class="mc-field-group">
            	<label for="mce-EMAIL">Email Address</label>
            	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
            </div>
          	<div id="mce-responses" class="clear">
          		<div class="response" id="mce-error-response" style="display:none"></div>
          		<div class="response" id="mce-success-response" style="display:none"></div>
          	</div>
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_899fd0460f56466751b56aea7_26e918e72d" tabindex="-1" value=""></div>
          </div>
          <span class="privacy-link"><%= link_to "We promise", privacy_policy_path %> not to spam you.</span>
          <div class="pricing-button">
            <div class="clear"><input type="submit" value="Submit Email" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
          </div>
        </form>
        </div>
        <!--End mc_embed_signup-->
        <!-- <label for="email">Email Address</label>
        <input type="email" name="email" id="email"/> -->
      </div>
    </div>
  </div>
</section>

app/views/book_sales/_testimonials.html.erb
<section class="testimonials">
  <div class="testimonial">
    <div class="quote">
      "I’m delighted with your book. The layout is brilliant and each step
      by step explanation is just perfect."
    </div>
    <div class="author">
      <img/>
      <a href="http://tomndi.blogspot.com">Tom, Canada</a>
    </div>
  </div>
  <div class="testimonial">
    <div class="quote"></div>
    <div class="author">
      <img/>
      <a href=""></a>
    </div>
  </div>
  <div class="testimonial">
    <div class="quote"></div>
    <div class="author">
      <img/>
      <a href=""></a>
    </div>
  </div>
</section>

app/views/book_sales/book.html.erb
<div class="page">
  <nav class="book-nav">
    <header class="navigation" role="banner">
      <div class="navigation-wrapper">
      <%= link_to root_path, class: "logo" do %>
        <%= inline_svg("edit_image.svg", class: 'nav-logo') %>
        <h1 id="nav-title">HOW TO GIMP</h1>
      <% end %>
      </div>
    </header>
  </nav>
  <div class="hero-image">
    <div class="hero-benefit-box">
      <h1>You
        <span class="small-caps type-letters">
          <span class="type-letter">C</span>
          <span class="type-letter">a</span>
          <span class="type-letter">n</span>
          <span class="cursor"></span>
        </span>
        Learn <span title="The Gnu Image Manipulation Program">GIMP</span></h1>
      <h3>Even if you're not a rocket scientist</h3>
      <a class="scroll-on-page-link" href="#scroll-link-1"><button class="cta-button">Buy the Book</button></a>
    </div>
  </div>
  <div class="how-it-works">
    <h2>How to GIMP</h2>
    <h3>A <span title="The Gnu Image Manipulation Program">GIMP</span> Book for Complete Beginners</h3>
    <div class="third">
      <div>1</div>
      <h3>Set Up GIMP</h3>
      <p>GIMP doesn't have to be so complicated. You'll learn GIMP's interface so you can find tools when you need them.</p>
    </div>
    <div class="third" >
      <div>2</div>
      <h3>Learn the Basics</h3>
      <p>This GIMP book doesn't assume you're a computer guru.
      Step-by-step instructions guide you through GIMP's tools and features.</p>
    </div>
    <div class="third">
      <div>3</div>
      <h3>Grow Your Skills</h3>
      <p>Combine your new GIMP skills to work through more advanced tutorials.
        30+ practice images make following along simple.</p>
    </div>
  </div>
  <%= render 'look_inside' %>
  <%= render "pricing" %>
  <footer></footer>
</div>
<%= render 'modal' %>

<script>
//Smooth Scroll
$(document).ready(function(){
  (function (jQuery) {
    jQuery.mark = {
      jump: function (options) {
        var defaults = {
          selector: 'a.scroll-on-page-link'
        };
        if (typeof options == 'string') {
          defaults.selector = options;
        }

        options = jQuery.extend(defaults, options);
        return jQuery(options.selector).click(function (e) {
          var jumpobj = jQuery(this);
          var target = jumpobj.attr('href');
          var thespeed = 1000;
          var offset = jQuery(target).offset().top;
          jQuery('html,body').animate({
            scrollTop: offset
          }, thespeed, 'swing');
          e.preventDefault();
        });
      }
    };
  })(jQuery);
  jQuery(function(){
    jQuery.mark.jump();
  });
});
</script>
<script>
$(document).ready(function() {

  var typeAnimation = function(){
    console.log("inside typeAnimation");
    $(".type-letter").each( function(index){
      $(this).hide();
    });
    $(".type-letter").each(function(index){
      $(this).delay(500*(index+1)).show(0);
    });
    setTimeout(typeAnimation, 5000);
  };
  typeAnimation();
});
</script>

app/views/layouts/_footer.html.erb
<footer class="footer" role="contentinfo">
  <div class="footer-logo">
    <%= image_tag 'dashboard/book.png' %>
  </div>
  <div class="footer-links">
    <ul>
      <li><h3>How to GIMP Book</h3></li>
      <li><%= link_to "Buy the Book", gimp_book_path %></li>
      <li><%= link_to "Get Practice Images", practice_images_path %></li>
      <li><%= link_to "Book FAQ", book_faq_path %></li>
    </ul>
    <ul>
      <li><h3>Connect</h3></li>
      <li><a href="https://www.pinterest.com/howtogimp/">Pinterest</a></li>
      <li><a href="https://www.youtube.com/c/howtogimp">YouTube</a></li>
      <li><a href="http://howtogimp.tumblr.com">Tumblr</a></li>
    </ul>
    <ul>
      <li><h3>Site Info</h3></li>
      <li>
        <a href="http://www.flaticon.com" title="Flaticon">
          <%= inline_svg 'edit_image.svg', class:"footer-list-icon" %> &
          <%= inline_svg 'dashboard/book-and-glasses.svg', class:"footer-list-icon", id:"book-and-glasses" %>
        </a>
        <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
      </li>
      <li><%= link_to 'Privacy Policy', privacy_policy_path %></li>
      <li><a href=""></a>©KatLandreth <%= Time.now.year %></li>
    </ul>
  </div>

</footer>

app/views/layouts/_index_paralax.html.erb
<div id="js-parallax-window" class="parallax-window">
  <div class="parallax-static-content">
    <div class="parallax-content-box">
    <b>Make Something Awesome</b>
  </div>
  </div>
  <div id="js-parallax-background" class="parallax-background"
  style='background: url("../assets/monitor_with_photo_of_mountains.jpg") repeat; background-size:cover;'></div>
</div>

app/views/layouts/_navbar.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">

  <%= link_to root_path, class: "logo" do %>
    <%= inline_svg("edit_image.svg", class: 'nav-logo') %>
    <h1 id="nav-title">HOW TO GIMP</h1>
  <% end %>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <!-- <div class="navigation-tools">
      <div class="search-bar">
        <form role="search">
          <input type="search" placeholder="Enter Search" />
          <button type="submit">
            <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png" alt="Search Icon">
          </button>
        </form>
      </div>
    </div> -->
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <li class="nav-link"><%= link_to 'Book', gimp_book_path %></li>
        <li class="nav-link"><a href="javascript:void(0)">Help</a></li>
        <li class="nav-link"><%= link_to "Contact", new_contact_message_path %></li>
        </ul>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_paralax.html.erb
<div id="js-parallax-window" class="parallax-window">
  <div class="parallax-static-content">
    <div class="parallax-content-box">
    <b>Make Something Awesome</b>
  </div>
  </div>
  <div id="js-parallax-background" class="parallax-background"
  style='background: url(<%= "#{@post.featured_image}" %>) repeat;'></div>
</div>

app/views/layouts/_show_paralax.html.erb
<div id="js-parallax-window" class="parallax-window">
  <div class="parallax-static-content">
    <div class="parallax-content-box">
    <%= @post.title %>
  </div>
  </div>
  <div id="js-parallax-background" class="parallax-background"
    style='background: url(<%= "#{@post.featured_image}" %>) repeat; background-size: cover;'></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <meta id="meta" name="viewport" content="width=device-width; initial-scale=1.0" />
  <%= csrf_meta_tags %>
</head>
<body class="type-system-rounded">
  <div id="rails-flash-message">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :class => "flash_#{name}" %>
      <% end %>
    <% end %>
  </div>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  <%= render 'layouts/footer' %>

<!-- Google Analytics Tracking -->
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-78990277-1', 'auto');
  ga('send', 'pageview');

  </script>
</body>
</html>

app/views/layouts/book.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GIMP Book</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta id="meta" name="viewport" content="width=device-width; initial-scale=1.0" />
    <%= csrf_meta_tags %>
  </head>
  <body class="type-system-rounded">
    <%= yield %>
    <!-- Google Analytics Tracking -->
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-78990277-1', 'auto');
    ga('send', 'pageview');

    </script>
    <script>
      $(document).ready(function(){
        $('.btn-look-inside').click(function(){
          $('#look-inside-modal').addClass('modal-active');
          $('.page').addClass('modal-active');
        });
        $('#look-inside-modal span').click(function(){
          $('#look-inside-modal').removeClass('modal-active');
          $('.page').removeClass('modal-active');
        })
      });
    </script>
    </script>
  </body>
</html>

app/views/posts/_content_nav.html.erb
<div class="content_nav">
  <nav>
    <ul>
      <li id="blog_tab" class="tab" data-post-type="blog">BLOG</li>
      <li id="tutorials_tab" class="active_tab tab" data-post-type="tutorial">TUTORIALS</li>
      <li id="book_tab" class="tab"><%= link_to 'GIMP BOOK', gimp_book_path%></li>
    </ul>
  </nav>
</div>

app/views/posts/_posts.html.erb
<div class="post_card_wrapper">
  <%= render "sort_and_filter" %>
  <div class="post_count"><h3><%= "#{@posts.count}" + " " +
 " " + "post".pluralize(@posts.count)%></h3>
 </div>
</div>
<% @posts.each do |post| %>
  <div class="post_card_wrapper">
    <%= link_to path_to_post(post) do %>
      <div class="post_card">
        <div class="post-excerpt-image">
          <img src="<%= post.featured_image%>"/>
        </div>
        <div class="post-excerpt">
          <%= render 'share_buttons' %>
          <h2><%= post.title %></h2>
          <p><%= truncate(strip_tags(markdown(post.payload)), length: 175, separator: ' ') %></p>
          <div class="post-tags"><%= show_tags(post) %></div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_pricing.html.erb
<section class="book-pricing">
  <hgroup><h2>Purchase Options</h2></hgroup>

  <div class="book-pricing-content">
    <div class="book-option">
        <h3>EPUB</h3>

        <span class="price"><sup class="dollar">$</sup>9.99</span>
        <ul>
          <li><em>Kindle</em> Optimised</li>
          <li><em>Instant</em> Download</li>
          <li><em>300+</em> Pages</li>
          <li><em>30+</em> Practice Images</li>
          <li><em>GIMP 2.8</em> Compatible</li>
        </ul>
        <div class="pricing-button">
          <button>Purchase Now</button>
        </div>
    </div>

    <div class="book-option">
      <h3>PDF EBOOK</h3>

      <span class="price"><sup class="dollar">$</sup>9.99</span>
      <ul>
        <li><em>Desktop</em> Optimised</li>
        <li><em>Instant</em> Download</li>
        <li><em>300+</em> Pages</li>
        <li><em>30+</em> Practice Imges</li>
        <li><em>GIMP 2.8</em> Compatible</li>
      </ul>
      <div class="pricing-button">
        <button>Purchase Now</button>
      </div>
    </div>

    <div class="book-option">
      <h3>Paperback Book</h3>
      <span class="coming-soon">Coming Soon</span>
      <div class="email-form">
        <label for="email">Email Address</label>
        <input type="email" name="email" id="email"/>
      </div>
      <div class="pricing-button">
        <button>Submit Email</button>
      </div>
    </div>
  </div>
</section>

app/views/posts/_sort_and_filter.html.erb
<div class="sort_and_filter">
  <%= form_tag filter_path, method: :get, remote: true, class: "sort-and-filter" do %>
    <div class="input-group">
      <%= label_tag "format"  %>
      <div class="select">
        <%= select_tag(:content_format,
        options_for_select([
          ["all (#{posts_of_type(@post_type).count})", "all"],
          ["video (#{count_all_posts_of_format('video', @post_type)})", "video"],
          ["written (#{count_all_posts_of_format('written', @post_type)})", "written"]
          ], "all")
          ) %>
        <div class="select__arrow"></div>
      </div>
    </div>
    <div class="input-group">
      <%= label_tag "category"  %>
      <div class="select">
        <%= select_tag(:tag, options_for_select(tag_filter(@post_type),  "All"), autocomplete: "off") %>
        <div class="select__arrow"></div>
      </div>
    </div>
    <div class="input-group">
      <%= label_tag "sort"  %>
      <div class="select">
        <%= select_tag(:order, options_for_select([["Newest First", "desc"], ["Oldest First", "asc"]], "Newest First"), autocomplete: "off") %>
        <div class="select__arrow"></div>
      </div>
    </div>
    <%= hidden_field_tag :post_type, "tutorial", id: "post_type_field" %>
    <%= submit_tag "", style: "display: none;" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= render 'layouts/index_paralax' %>
<%= render 'content_nav' %>
<div class="post-container">
  <div class="posts">
    <%= render "posts" %>
  </div>
</div>

app/views/posts/index_o.html.erb
<%= render 'layouts/index_paralax' %>
<div class="featured-posts">
  <% @posts[0..2].each do |post| %>
  <div class="post-excerpt">
    <%= link_to path_to_post(post) do %>
      <div class="post-excerpt-title">
        <h2><%= post.title %></h2>
        <h3>A Subtitle</h3>
      </div>
      <div class="post-excerpt-image">
        <img src="http://brixton.premiumcoding.com/wp-content/uploads/2015/02/featured-image-1.jpg"/>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<%= render "layouts/show_paralax" %>
<div class="show-post">
  <%= markdown(@post.payload) %>
  <hr>
  <div class="discus-wrapper">
    <%= disqus_init :short_name => "howtogimp",
                    :public_key => "",
                    :secret_key => "",
                    :access_token => "" %>
    <%- disqus_thread %>
  </div>
</div>