dashboard/config/routes.rb
Dashboard::Engine.routes.draw do

  devise_for :users, class_name: "Dashboard::User", module: :devise
  get 'tags/:tag', to: 'entries#index', as: "tag"
  get 'media-library/:entry_id', to: 'media#index', as: "media_library"
  get 'media-show/:id/:entry_id', to: 'media#show', as: "media_show"
  get 'media-new/:entry_id', to: 'media#new', as: "media_new"
  get 'analytics', to: 'analytics#index', as: 'analytics_dashboard'

  resources :media do
    collection do
      delete :destroy_multiple
    end
  end
  resources :entries do
    get 'preview'
    patch 'publish'
    collection do
      delete :destroy_multiple
    end
  end

 root to: 'entries#index'
end

dashboard/app/models/dashboard/entry.rb
module Dashboard
  class Entry < ActiveRecord::Base
    include Dashboard::MarkdownHelper

    has_drafts
    has_many :taggings
    has_many :tags, through: :taggings

    validates :published_at, absence: { message: "body can't be blank"}, unless: :payload?
    validates :published_at, absence: { message: "featured image can't be blank"}, unless: :featured_image?

    # def published
    #   Dashboard::Entry.published
    # end

    def self.tagged_with(name)
      if name != "all"
        joins(:tags).where("name = ?", name )
      else
        all
      end
    end

    def self.post_type(type = 'tutorial')
      if type.size > 0
        self.where(post_type: type)
      elsif self.count > 0
        self.first[:post_type]
      end
    end

    def self.content_format(c_format = 'all')
      if c_format != "all"
        where(content_format: c_format)
      else
        all
      end
    end

    def self.sorted_by(order)
       self.order(:published_at => order)
    end

    def all_tags=(names)
      self.tags = names.split(",").map do |name|
        Dashboard::Tag.where(name: name.strip).first_or_create!
      end
    end

    def all_tags
      self.tags.map(&:name).join(", ")
    end
  end
end

dashboard/app/models/dashboard/medium.rb
module Dashboard
  class Medium < ActiveRecord::Base
    mount_uploader :file, Dashboard::ImageUploader
  end
end

dashboard/app/models/dashboard/seo_analyzer.rb
module Dashboard
  class SeoAnalyzer < WordsCounted::Counter
    attr_accessor :string

    def initialize(string = 'There is no body yet, please write some content. For another thing, write some more.')
      @string = string.gsub(/src.+[\.][\w]{3}["|']/i, '')
    end

    def word_count(string = @string)
      tokenize_words(string)
      @counter.token_count
    end

    def sentence_count
      @string.strip.split(/\w[?!.]/).length
    end

    def words
      @words = []
      word_analysis(@string)
      @analysis.each_pair { |word, values| @words.push SeoWord.new(word, values[:frequency], values[:density])}
      @words
    end

    def readibility_score
      raw_score = 206.835 - (1.015 * asl) - (84.6 * asw)
      raw_score.to_int
    end

    def score_meaning
      if readibility_score.between?(90,100)
        "very easy"
      elsif readibility_score.between?(80,89)
        "easy"
      elsif readibility_score.between?(70,79)
        "fairly easy"
      elsif readibility_score.between?(60,69)
        "standard"
      elsif readibility_score.between?(50,59)
        "fairly difficult"
      elsif readibility_score.between?(30,49)
        "difficult"
      elsif readibility_score.between?(0,29)
        "very confusing"
      end

    end


    private

    def tokenize_words(string = @string, exclude = html_tags)
      @counter = WordsCounted.count(string, exclude: exclude)
    end

    def total_syllables
      tokenize_words(@string, html_tags)
      sum = []
      @counter.token_frequency.each do |word, freq|
        sum.push SeoWord.new(word).syllables * freq
      end
      sum.reduce(0, :+)
    end

    def asw
      total_syllables.to_f / word_count.to_f
    end

    def asl
      word_count.to_f / sentence_count.to_f
    end

    def word_analysis(string = @string)
      @analysis = {}
      tokenize_words(string, html_and_stop_words)
      @counter.token_frequency.each { |word, freq| @analysis[word] = {frequency: freq} }
      @counter.token_density.each   { |word, dens| @analysis[word][:density] = dens }
      @analysis
    end

    def word_density(string)
      tokenize_words(string, html_and_stop_words)
      @counter.token_density
    end

    def word_frequency(string)
      tokenize_words(string, html_and_stop_words)
      @counter.token_frequency
    end

    def exclude_img_attrs
      /src.+[\.][\w]{3}["|']/i
     end

    def html_tags
      ["figcaption", "figure", "amazonaws", "https", "booqcms", "class",
        "inline-image", "id", "src", "href", "alt", "title", "description",
        "allowfullscreen", "frameborder", "www", "png", "jpg", "gif", "iframe",
        "youtube", "uploads", "target", "blank", "embed", "xs", "''", "'blank'",
        "video", "video-wrapper", "img", "com"]
    end


    def stop_words
        %w(a about above after again against all am an and any are aren't as at be because
        been before being below between both but by can't cannot could couldn't did
        didn't do does doesn't doing don't down during each few for from further had
        hadn't has hasn't have haven't having he he'd he'll he's her here here's hers
        herself him himself his how how's i i'd i'll i'm i've if in into is isn't it
        it's its itself let's me more most mustn't my myself no nor not of off on once
        only or other ought our ours 	ourselves out over own same shan't she she'd
        she'll she's should shouldn't so some such than that that's the their theirs
        them themselves then there there's these they they'd they'll they're they've
        this those through to too under until up very was wasn't we we'd we'll we're
        we've were weren't what what's when when's where where's which while who who's
        whom why why's with won't would wouldn't you you'd you'll you're you've your
        yours yourself yourselves)
    end

    def html_and_stop_words
      html_tags.concat stop_words
    end

    class SeoWord < SeoAnalyzer
      attr_accessor :word, :frequency, :density

      def initialize(word, frequency = 0, density = 0)
        @word = word
        @frequency = frequency
        @density = density
      end
      def syllables
        word_dup = @word.dup
        return 1 if word_dup.length <= 3
        word_dup.sub!(/(?:[^laeiouy]es|ed|[^laeiouy]e)$/, '')
        word_dup.sub!(/^y/, '')
        word_dup.scan(/[aeiouy]{1,2}/).size
      end
    end
  end
end

dashboard/app/models/dashboard/tag.rb
module Dashboard
  class Tag < ActiveRecord::Base
    has_many :taggings
    has_many :entries, through: :taggings
  end
end

dashboard/app/models/dashboard/tagging.rb
module Dashboard
  class Tagging < ActiveRecord::Base
    belongs_to :entry, :class_name => "Dashboard::Entry"
    belongs_to :tag, :class_name => "Dashboard::Tag"
  end
end

dashboard/app/models/dashboard/user.rb
module Dashboard
  class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
  end
end

dashboard/app/controllers/dashboard/analytics_controller.rb
require_dependency "dashboard/application_controller"

module Dashboard
  class AnalyticsController < ApplicationController

    def index
    end

  end
end

dashboard/app/controllers/dashboard/application_controller.rb
module Dashboard
  class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    protect_from_forgery with: :exception

  def content_entries_path
   entries_path
  end
  helper_method :content_entries_path

  def content_entry_path(entry)
    entry_path(entry)
  end
  helper_method :content_entry_path
  end
end

dashboard/app/controllers/dashboard/entries_controller.rb
require_dependency "dashboard/application_controller"

module Dashboard
  class EntriesController < ApplicationController
    respond_to :html, :json, :js
    before_action :set_entry, only: [:show, :edit, :update, :destroy]
    before_filter :reify_entry, only: [:show, :edit]

    def index
      if params[:tag]
        @entries = Entry.tagged_with(params[:tag])
      else
        @entries = Entry.all
      end
    end

    def show
    end

    def new
      @entry = Entry.new
    end

    def create
      @entry = Entry.new(entry_params)
      if @entry.draft_creation
        redirect_to edit_entry_path(@entry[:id]), :notice => "The Draft was Saved!", :format => :json
      else
        render :action => "new", :notice => "didn't save"
      end
    end

    def edit
    end

    def update
     @entry.attributes = entry_params
     if @entry.draft_update
        flash.now[:success] = 'a draft of this entry was saved'
        render :edit
      else
        flash.now[:error] = 'there was an error saving this draft'
        render :edit
      end
    end

    def preview
      @entry = Entry.find(params[:entry_id])
      reify_entry
      respond_to do |format|
        format.js {render layout: false}
      end
      # respond_with @entry
    end

    def destroy
      @entry.destroy
      redirect_to content_entries_path, notice: 'Entry was successfully destroyed.'
    end

    def destroy_multiple
      Entry.destroy(params[:entry_ids])
      redirect_to content_entries_path, notice: 'Entries were successfully destroyed.'
    end

    def publish
      @entry = Entry.find(params[:entry_id])
      if @entry.draft?
        @entry.draft.publish!
        respond_with(@entry, :location => edit_entry_path(@entry.id))
      else
        @entry.published_at = Time.now
        @entry.save!
        respond_with(@entry, :location => edit_entry_path(@entry.id))
      end
    end

    private

    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      allowed_attrs = %i(id category title slug published_at payload featured_image all_tags author_name post_type content_format)
      params.require(:entry).permit(*allowed_attrs)
    end

    def reify_entry
      @entry = @entry.draft.reify if @entry.draft?
    end
  end
end

dashboard/app/controllers/dashboard/media_controller.rb
require_dependency "dashboard/application_controller"

module Dashboard
  class MediaController < ApplicationController
    respond_to :html, :json, :js
    before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    if params[:entry_id]
      @entry = Entry.find(params[:entry_id])
    end
    @uploads = Medium.paginate(per_page: 8, page: params[:page]).order('id DESC')
    respond_to do |format|
      format.html
      format.js { respond_with @uploads }
    end
  end

  def show
    if params[:entry_id]
      @entry = Entry.find(params[:entry_id])
    end
    respond_with @upload
  end

  def new
    if params[:entry_id]
      @entry = Entry.find(params[:entry_id])
    end
    @upload = Medium.new
    respond_with @upload
  end

  def edit
  end

  def create
    if params[:entry_id]
      @entry = Entry.find(params[:entry_id])
    end
  @upload = Medium.create(media_upload_params)
     if @upload.save
      @uploads = Medium.paginate(per_page: 8, page: params[:page]).order('id DESC')
      respond_to do |format|
        format.html { redirect_to media_url }
        format.js { render :index }
      end
     end
  end

  def update
    if @upload.update(post_upload_params)
      redirect_to @upload, notice: 'Upload attachment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /uploads/1
  def destroy
    @upload.destroy
    redirect_to media_url, notice: 'Upload was successfully destroyed.'
  end

  def destroy_multiple
    Medium.destroy(params[:medium_ids])
    redirect_to media_url, notice: 'Media was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @upload = Medium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def media_upload_params
      params.require(:medium).permit(:title, :description, :file)
    end
  end
end

dashboard/app/helpers/dashboard/application_helper.rb
module Dashboard
  module ApplicationHelper
  end
end

dashboard/app/helpers/dashboard/entries_helper.rb
module Dashboard
  module EntriesHelper

    def new_entry_path
      dashboard.new_entry_path
    end

    def media_path
      dashboard.media_path
    end


    def grid_item_box(entry)
      render "index_item", entry: entry
    end

    def post_status_class(entry)
      if entry.published_at
        "badge-success"
      else
        "badge-alert"
      end
    end

    def post_status(entry)
      if entry.published_at != nil
        "published"
      else
        "draft"
      end
    end

    def publish_status(entry)
      render 'publish_button'
    end

    def preview_featured_image(entry)
      if entry.featured_image != nil
        return_html = '<img src="' + entry.featured_image + '" width="700" />'
        return_html.html_safe
      else
        '[No Featured Image Set]'
      end
    end

    def tag_links(tags)
      tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip)}.join(", ")
    end

    def seo_analysis
      if @entry.payload != nil
        SeoAnalyzer.new(@entry.payload)
      else
        SeoAnalyzer.new("No body found.")
      end
    end

  end
end

dashboard/app/helpers/dashboard/markdown_helper.rb
module Dashboard
  module MarkdownHelper
    class HTMLwithCoderay < ::Redcarpet::Render::HTML
      include ::Redcarpet::Render::SmartyPants

      def block_code(code, language)
        CodeRay.scan(code, language).div
      end
    end

    def markdown(text)
      renderer = HTMLwithCoderay.new(hard_wrap: false, filter_html: false)
      options = {
        filter_html: false,
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        tables: true,
        footnotes: true
      }
      ::Redcarpet::Markdown.new(renderer, options).render(text.to_s).html_safe
    end
  end
end

dashboard/app/helpers/dashboard/media_helper.rb
module Dashboard
  module MediaHelper
  end
end

dashboard/app/helpers/dashboard/publish_status.rb
def publish_status(entry)
  # if entry.published_at != nil
  #   render 'published_notice'
  # else
    render 'publish_button'
  # end
end

dashboard/app/helpers/dashboard/will_paginate_helper.rb
module Dashboard
  module WillPaginateHelper
    class WillPaginateJSLinkRenderer < WillPaginate::ActionView::LinkRenderer
      def prepare(collection, options, template)
        options[:params] ||= {}
        options[:params]['_'] = nil
        super(collection, options, template)
      end

      protected
      def link(text, target, attributes = {})
        if target.is_a? Fixnum
          attributes[:rel] = rel_value(target)
          target = url(target)
        end

        @template.link_to(target, attributes.merge(remote: true)) do
          text.to_s.html_safe
        end
      end
    end

    def js_will_paginate(collection, options = {})
      will_paginate(collection, options.merge(:renderer => WillPaginateHelper::WillPaginateJSLinkRenderer))
    end
  end
end

dashboard/app/views/dashboard/media/_index.html.erb
<% @uploads.each do |upload| %>
  <%= link_to media_show_path(id: upload.id, entry_id: @entry.id), format: :js, remote: true do %>
    <div class="gallery-thumb-wrapper">
      <img src="<%= upload.file.thumb %>">
      <div class="gallery-thumb-name">
        <%= truncate(upload.file.file.filename, length:20) %>
      </div>
    </div>
  <% end %>

<% end %>
<%= js_will_paginate @uploads %>

dashboard/app/views/dashboard/media/_new.html.erb
<%= form_for(@upload, url: {controller: "media", action: "create", :format => :js, entry_id: @entry.id}, remote: true, authenticity_token: true) do |f| %>
  <div>
  </br>
    <%= f.file_field :file, class: "file" %>
    <%= button_tag 'Cancel', type: 'reset', id: 'cancel-upload' %>
  </div>
  <div>
    <%= f.submit class: "upload-submit" %>
  </div>
<% end %>

dashboard/app/views/dashboard/media/_show.html.erb
<span>use this image</span>
<img src="<%= @upload.file.thumb %>" /><br/>
<hr>

<%= form_for @entry, url: {controller: "entries", action: "update", id: @entry.id}, method: "patch" do |f| %>
  <%= f.hidden_field :featured_image, value: @upload.file %>
  <%= f.submit "Use as Featured Image" %>
<% end %>

<div class="image_embed_form">
  <input type="hidden" id="image-src-field" value="<%= @upload.file %>"/>
  <input type="text" title="caption" id="image-caption-field" name="caption" placeholder="caption" />
  <input type="text" title="alt" id="image-alt-field" name="alt" placeholder="alt text (for SEO and screen readers)" />
  <input type="text" title="title" id="image-title-field" name="title" placeholder="title- will be used in a tooltip" />
  <input type="text-box" title="description" id="image-description-field" name="description" placeholder="describe the image (for SEO and screen readers)" />
  <input type="submit" class="submit" value ="Generate Markup for Image" return="false"/>
</div>

dashboard/app/views/dashboard/media/index.html.erb
<section class="media-library">
  <h2>Media Library</h2>
  <div class="gallery-thumb-wrapper">
    <%= link_to new_medium_path, class: "primary-button", id: "new-image-button" do %>
      <h3>Upload Image</h3> <br>
      <%= inline_svg("dashboard/plusicon.svg", class: 'content-component-svg') %>
    <% end %>
  </div>
    <%= form_tag destroy_multiple_media_path, class: "delete-images-form", method: :delete do %>
      <% @uploads.each do |upload| %>
        <div class="gallery-thumb-wrapper">
          <%= check_box_tag "medium_ids[]", upload.id, false, :class => "multi-delete-checkbox", :id => "medium_ids_#{upload.id}"%>
          <%= link_to upload do %>
            <img src="<%= upload.file.thumb %>">
            <div class="gallery-thumb-name">
              <%= truncate(upload.file.file.filename, length:20) %>
            </div>
          <% end %>
        </div>
      <% end %>
      <%= submit_tag "delete selected", :class => "multi-delete-submit", data: { confirm: 'You sure about that boss?' } %>
    <% end %>
    <%= will_paginate @uploads %>
    <br>
</section>

dashboard/app/views/dashboard/media/index.js.erb
$(".image-gallery").html("<%= escape_javascript(render partial: '/dashboard/media/index') %>");
$(".upload-preview img").removeAttr("src");
$("#modal-2").prop('checked', true);
NProgress.done();

dashboard/app/views/dashboard/media/new.html.erb
<section class="media-library">
  <div class="upload-form">
    <div class="uploaded-image"></div>
    <div class="upload-preview">
      <img />
    </div>
    <%= form_for(@upload, url: {controller: "media", action: "create", :format => :html}, remote: false, authenticity_token: true) do |f| %>
      <div>
        <%= f.label :file %><br>
        <%= f.file_field :file, class: "file" %>
      </div>
      <div>
        <%= f.submit %> <%= button_tag 'Cancel', type: 'reset', id: 'cancel-upload' %>
      </div>
    <% end %>
  </div>
</section>

dashboard/app/views/dashboard/media/new.js.erb
$(".upload_form").html("<%= escape_javascript(render partial: '/dashboard/media/new') %>");
$(".button-card").hide();

dashboard/app/views/dashboard/media/show.html.erb
<section>
  <%= link_to "Back to Library", media_path %>
  <h2><%= @upload.file.file.filename %></h2>
  <img src="<%= @upload.file.thumb %>" /><br/>
</section>

dashboard/app/views/dashboard/media/show.js.erb
$(".uploaded-image").html('<%= escape_javascript(render partial: "/dashboard/media/show", locals: { upload: @upload } ) %>');
$(".upload-preview img").removeAttr("src");